### ISSUE TITLE
ValueError: Unknown endpoint type: '7077'

### ISSUE THREAD

**Issue by markmark1** [djacobs/PyAPNs#206]
twistd -r epoll web --class=pyapns.server.APNSServer --port=7077
Traceback (most recent call last):
  File "/usr/bin/twistd", line 11, in <module>
    sys.exit(run())
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/usr/lib64/python2.7/site-packages/twisted/web/tap.py", line 245, in makeService
    strports.service(config['port'], site).setServiceParent(s)
  File "/usr/lib64/python2.7/site-packages/twisted/application/strports.py", line 40, in service
    endpoints.serverFromString(reactor, description), factory)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1702, in serverFromString
    nameOrPlugin, args, kw = _parseServer(description, None)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1620, in _parseServer
    getPlugins(IStreamServerEndpointStringParser), endpointType
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1636, in _matchPluginToPrefix
    raise ValueError("Unknown endpoint type: '%s'" % (endpointType,))
ValueError: Unknown endpoint type: '7077'

**Comment by markmark1** [comment]
get this error please help

**Comment by ks1322** [comment]
should work with `--port="tcp:port=7077"`
taken from here https://github.com/robgjansen/onionperf/issues/26#issuecomment-306858519
