### ISSUE TITLE
In enhanced mode, connection will enter bad state and stop sending notification after connection idles for more than 2 hours

### ISSUE THREAD

**Issue by jimhorng** [djacobs/PyAPNs#94]
The connection might be broken but the library is not awared, and error-response worker might hang and cause connection not function properly, then, send notification with the same connection will be blocked.

**Comment by kelonye** [comment]
Still experiencing this. First message is sent successfully but subsequent ones fail with:

```
[Errno 22] Invalid argument
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
    run(self.request.body)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
    return func(*args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 190, in invoke_member
    return getattr(obj, membername)(*args, **kwargs)
  File "/base/data/home/apps/s~yida-kelonye/1.381243078546549010/server/models.py", line 765, in _apn
    APNS.gateway_server.send_notification_multiple(frame)
  File "/base/data/home/apps/s~yida-kelonye/1.381243078546549010/server/lib/apns/__init__.py", line 549, in send_notification_multiple
    return self.write(frame.get_frame())
  File "/base/data/home/apps/s~yida-kelonye/1.381243078546549010/server/lib/apns/__init__.py", line 260, in write
    _, wlist, _ = select.select([], [self._connection()], [], WAIT_WRITE_TIMEOUT_SEC)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 493, in select
    raise _SystemExceptionFromAppError(e)
error: [Errno 22] Invalid argument
```

This is in GAE btw.

**Comment by jimhorng** [comment]
As your log shows, you are using enhanced mode with frames, which is NOT currently supported, see #90, there's patch already but not merged to 'master' branch yet.

**Comment by kelonye** [comment]
Thanks mate!
